version: '3'
services:
  php:
    build:
      context: .docker/php
    working_dir: /var/www/web-crawler-service
    volumes:
      - ./:/var/www/web-crawler-service
    ports:
      - "9000:9000"
    environment:
      # unlimited
      - COMPOSER_MEMORY_LIMIT=-1
  rabbit_mq:
    build:
      context: .docker/rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: crawler
      RABBITMQ_DEFAULT_PASS: UMHXuMhbQypZwP

  redis-cluster:
    build:
      context: .docker/redis
    volumes:
      - .docker/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "7000:7000"
    environment:
      STANDALONE: 'true'
      MASTERS: 3
      SLAVES_PER_MASTER: 1

  redisinsight:
    build:
      context: .docker/redisinsight
    ports:
      - 8001:8001
    depends_on:
      - redis-cluster

  worker:
    restart: always
    build:
      context: .docker/php
    working_dir: /var/www/web-crawler-service
    volumes:
      - ./:/var/www/web-crawler-service
    entrypoint: ["php", "bin/console", "messenger:consume", "async", "-vv"]
    depends_on:
      - php
      - redis-cluster
      - rabbit_mq
    deploy:
      mode: replicated
      replicas: 3

# docker-compose run php bin/console messenger:consume async -vv
# redis-cli -h 127.0.0.1 -p 22121
