version: '3'
services:
  php:
    build:
      context: .docker/php
    working_dir: /var/www/web-crawler-service
    volumes:
      - ./:/var/www/web-crawler-service
    ports:
      - "9000:9000"
    networks:
      - elastic
    environment:
      # unlimited
      - COMPOSER_MEMORY_LIMIT=-1
  rabbit_mq:
    build:
      context: .docker/rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: crawler
      RABBITMQ_DEFAULT_PASS: UMHXuMhbQypZwP

  redis-cluster:
    build:
      context: .docker/redis
    volumes:
      - .docker/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "7000:7000"
    environment:
      STANDALONE: 'true'
      MASTERS: 3
      SLAVES_PER_MASTER: 1

  redisinsight:
    build:
      context: .docker/redisinsight
    ports:
      - 8001:8001
    depends_on:
      - redis-cluster

#  worker:
#    restart: always
#    build:
#      context: .docker/php
#    working_dir: /var/www/web-crawler-service
#    volumes:
#      - ./:/var/www/web-crawler-service
#    entrypoint: ["php", "bin/console", "messenger:consume", "async", "-vv"]
#    depends_on:
#      - php
#      - redis-cluster
#      - rabbit_mq
#    deploy:
#      mode: replicated
#      replicas: 3

  es01:
    build: .docker/elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .docker/elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    build: .docker/elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .docker/elasticsearch/data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  es03:
    build: .docker/elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .docker/elasticsearch/data03:/usr/share/elasticsearch/data
    networks:
      - elastic


  elasticsearch_hq:
    build: .docker/elasticsearch_hq
    container_name: elasticsearch_hq
    environment:
      - "HQ_DEFAULT_URL=http://es01:9200"
    ports:
      - 5000:5000
    networks:
      - elastic
    depends_on:
      - es01
      - es02

networks:
  elastic:
    driver: bridge

# docker-compose run php bin/console messenger:consume async -vv
# redis-cli -h 127.0.0.1 -p 22121
